# ============================================================================
# HOME ASSISTANT LIGHT GROUPS
# ============================================================================
#
# Layer 1 (Subgroups): Managed in Zigbee2MQTT groups
# Layer 2 (Room groups): Defined below, combining Z2M groups + individual lights
#
# All groups have unique_id for UI editability
#

# =============================================================================
# HAUPTLICHTER - Raum-Aggregation (using Z2M subgroups)
# =============================================================================

- platform: group
  unique_id: alle_wohnzimmer_lichter
  name: Alle Wohnzimmer Lichter
  entities:
    # Wohnzimmer Wand (6 lights)
    - light.wohnzimmer_wand_1
    - light.wohnzimmer_wand_2
    - light.wohnzimmer_wand_3
    - light.wohnzimmer_wand_4
    - light.wohnzimmer_wand_5
    - light.wohnzimmer_wand_6
    # Wohnzimmer Esstisch (3 lights)
    - light.wohnzimmer_esstisch_1
    - light.wohnzimmer_esstisch_2
    - light.wohnzimmer_esstisch_3
    # Wohnzimmer Spielematte (4 lights)
    - light.wohnzimmer_spielematte_1
    - light.wohnzimmer_spielematte_2
    - light.wohnzimmer_spielematte_3
    - light.wohnzimmer_spielematte_4
    # Wohnzimmer Schrank (3 lights)
    - light.wohnzimmer_schrank_1
    - light.wohnzimmer_schrank_2
    - light.wohnzimmer_schrank_3
    # Individual light
    - light.wohnzimmer_spieletisch

- platform: group
  unique_id: alle_wohnzimmer_lichter_ohne_esstisch
  name: Alle Wohnzimmer Lichter ohne Esstisch
  entities:
    # Wohnzimmer Wand (6 lights)
    - light.wohnzimmer_wand_1
    - light.wohnzimmer_wand_2
    - light.wohnzimmer_wand_3
    - light.wohnzimmer_wand_4
    - light.wohnzimmer_wand_5
    - light.wohnzimmer_wand_6
    # Wohnzimmer Spielematte (4 lights)
    - light.wohnzimmer_spielematte_1
    - light.wohnzimmer_spielematte_2
    - light.wohnzimmer_spielematte_3
    - light.wohnzimmer_spielematte_4
    # Wohnzimmer Schrank (3 lights)
    - light.wohnzimmer_schrank_1
    - light.wohnzimmer_schrank_2
    - light.wohnzimmer_schrank_3
    # Individual light
    - light.wohnzimmer_spieletisch

- platform: group
  unique_id: alle_kuche_lichter
  name: Alle Kuche Lichter
  entities:
    # K端che Decke (2 lights)
    - light.kuche_decke_1
    - light.kuche_decke_2
    # K端che Insel (2 lights)
    - light.kuche_insel_oben
    - light.kuche_insel_unten
    # K端che Schrank (2 lights)
    - light.kuche_schrank_1
    - light.kuche_schrank_2

- platform: group
  unique_id: alle_schlafzimmer_lichter
  name: Alle Schlafzimmer Lichter
  entities:
    # Schlafzimmer Decke (2 lights)
    - light.schlafzimmer_decke_1
    - light.schlafzimmer_decke_2
    # Individual lights
    - light.schlafzimmer_bett
    - light.schlafzimmer_tv

- platform: group
  unique_id: alle_kinderzimmer_lichter
  name: Alle Kinderzimmer Lichter
  entities:
    - light.kinderzimmer_decke
    - light.kinderzimmer_bucher
    - light.kinderzimmer_schrank

- platform: group
  unique_id: alle_badezimmer_lichter
  name: Alle Badezimmer Lichter
  entities:
    # Badezimmer Decke (2 lights)
    - light.badezimmer_decke_1
    - light.badezimmer_decke_2
    # Individual lights
    - light.badezimmer_schrank
    - light.badezimmer_fenster

- platform: group
  unique_id: alle_arbeitszimmer_lichter
  name: Alle Arbeitszimmer Lichter
  entities:
    # Individual light
    - light.arbeitszimmer_decke
    # Arbeitszimmer PC (2 lights)
    - light.arbeitszimmer_pc_1
    - light.arbeitszimmer_pc_2
    # Individual light
    - light.arbeitszimmer_stehlampe

- platform: group
  unique_id: alle_flur_lichter
  name: Alle Flur Lichter
  entities:
    # Flur Decke (6 lights)
    - light.flur_decke_1
    - light.flur_decke_2
    - light.flur_decke_3
    - light.flur_decke_4
    - light.flur_decke_5
    - light.flur_decke_6
    # Flur Schrank (2 lights)
    - light.flur_schrank_1
    - light.flur_schrank_2

- platform: group
  unique_id: alle_ankleide_lichter
  name: Alle Ankleide Lichter
  entities:
    # Ankleide Decke (2 lights)
    - light.ankleide_decke_1
    - light.ankleide_decke_2

- platform: group
  unique_id: alle_waschzimmer_lichter
  name: Alle Waschzimmer Lichter
  entities:
    - light.waschzimmer_decke

- platform: group
  unique_id: alle_balkon_lichter
  name: Alle Balkon Lichter
  entities:
    # Balkon Wand (2 lights)
    - light.balkon_wand_1
    - light.balkon_wand_2
    # Individual light
    - light.balkon_blumen

# =============================================================================
# NACHTLICHTER - Separate Gruppen fuer Nachtmodi
# =============================================================================

- platform: group
  unique_id: alle_wohnzimmer_nachtlichter
  name: Alle Wohnzimmer Nachtlichter
  entities:
    # Wohnzimmer Schrank (3 lights)
    - light.wohnzimmer_schrank_1
    - light.wohnzimmer_schrank_2
    - light.wohnzimmer_schrank_3

- platform: group
  unique_id: alle_kuche_nachtlichter
  name: Alle Kuche Nachtlichter
  entities:
    # K端che Schrank (2 lights)
    - light.kuche_schrank_1
    - light.kuche_schrank_2
    # Individual light
    - light.kuche_insel_oben

- platform: group
  unique_id: alle_schlafzimmer_nachtlichter
  name: Alle Schlafzimmer Nachtlichter
  entities:
    - light.schlafzimmer_bett

- platform: group
  unique_id: alle_kinderzimmer_nachtlichter
  name: Alle Kinderzimmer Nachtlichter
  entities:
    - light.kinderzimmer_bucher
    - light.kinderzimmer_schrank

- platform: group
  unique_id: alle_badezimmer_nachtlichter
  name: Alle Badezimmer Nachtlichter
  entities:
    - light.badezimmer_schrank
    - light.badezimmer_fenster

- platform: group
  unique_id: alle_arbeitszimmer_nachtlichter
  name: Alle Arbeitszimmer Nachtlichter
  entities:
    # Arbeitszimmer PC (2 lights)
    - light.arbeitszimmer_pc_1
    - light.arbeitszimmer_pc_2
    # Individual light
    - light.arbeitszimmer_stehlampe

- platform: group
  unique_id: alle_flur_nachtlichter
  name: Alle Flur Nachtlichter
  entities:
    # Flur Schrank (2 lights)
    - light.flur_schrank_1
    - light.flur_schrank_2
